spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecourse?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 523521lx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true