spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/ecourse?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: L3054
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /download/**
  resources:
    static-locations: file:D:/upload/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#临时目录
server:
  tomcat:
    basedir: D:/lx78Temp


